version: '2'
services:
  microbiome:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - "TERM=xterm"
  microbiome-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./mb_webapp"]
    ports:
    - "8080:8080"
